<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Access\AccessResult;

/**
 * Implements hook_entity_presave().
 * 
 * @param EntityInterface $entity
 */
function dyniva_content_hub_entity_presave(EntityInterface $entity){
  $site_uuid = \Drupal::request()->headers->get('X-Site-ID');
  if ($site_uuid){
    $site = \Drupal::entityManager()->loadEntityByUuid('node', $site_uuid);
    if ($site){
      if (method_exists($entity, 'hasField') && $entity->hasField('site_ref')) {
        $entity->site_ref->target_id = $site->id();
      }
      if (method_exists($entity, 'hasField') && $entity->hasField('department') && $site->hasField('department') && !$site->get('department')->isEmpty()) {
        $entity->department = $site->department;
      }
    }
  }
}
